{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy\
\
WORKDIR /app\
\
COPY requirements.txt .\
RUN pip install --no-cache-dir -r requirements.txt\
\
COPY . .\
\
EXPOSE 10000\
\
CMD ["uvicorn", "main.py:app", "--host", "0.0.0.0", "--port", "10000"]}